### ISSUE TITLE
error using gbk.

### ISSUE THREAD

**Issue by ohlab** [tseemann/snippy#152]
When I provide a gbk reference input, I get the following error below. This did not occur using a fasta reference. 
Thanks.

java.lang.RuntimeException: Error parsing property 'ref.AE015924.codonTable'. No such codon table 'Bacterial_and_Plant_Plastid'
        at org.snpeff.snpEffect.Config.createCodonTables(Config.java:169)
        at org.snpeff.snpEffect.Config.readConfig(Config.java:650)
        at org.snpeff.snpEffect.Config.init(Config.java:480)
        at org.snpeff.snpEffect.Config.<init>(Config.java:117)
        at org.snpeff.SnpEff.loadConfig(SnpEff.java:451)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:364)
        at org.snpeff.SnpEff.run(SnpEff.java:1183)
        at org.snpeff.SnpEff.main(SnpEff.java:162)

**Comment by tseemann** [comment]
Can you paste the `snps.log` files?

It sounds like a problem with `snpeff`
How did you install `snpeff`?  What version?

**Comment by sbridel** [comment]
Same problem here when I try to launch with GBK ref file.

INSTALL
```
conda install -c bioconda -c conda-forge snippy
Fetching package metadata .................
Solving package specifications: .
Package plan for installation in environment /home/sebastien/anaconda3:
The following NEW packages will be INSTALLED:

    bcftools:            1.8-1               bioconda   
    bwa:                 0.7.17-pl5.22.0_2   bioconda   
    bzip2:               1.0.6-1             conda-forge
    freebayes:           1.1.0-py36_3        bioconda   
    htslib:              1.3.2-0             bioconda   
    java-jdk:            8.0.92-1            bioconda   
    libdeflate:          0.8-0               bioconda   
    ncurses:             5.9-10              conda-forge
    parallel:            20170422-pl5.22.0_0 bioconda   
    perl:                5.22.0.1-0          conda-forge
    perl-app-cpanminus:  1.7043-pl5.22.0_0   bioconda   
    perl-bioperl:        1.6.924-4           bioconda   
    perl-exporter-tiny:  0.042-1             bioconda   
    perl-file-slurp:     9999.19-0           bioconda   
    perl-list-moreutils: 0.428-pl5.22.0_0    bioconda   
    perl-threaded:       5.22.0-pl5.22.0_12  bioconda   
    perl-time-piece:     1.27-pl5.22.0_0     bioconda   
    perl-yaml:           1.24-0              bioconda   
    samclip:             0.2-pl5.22.0_0      bioconda   
    samtools:            1.8-3               bioconda   
    snippy:              4.0_dev-pl5.22.0_0  bioconda   
    snpeff:              4.3-3               bioconda   
    vcflib:              1.0.0_rc1-1         bioconda   

The following packages will be UPDATED:

    conda:               4.3.31-py36_0                   --> 4.5.1-py36_0 conda-forge
    pycosat:             0.6.1-py36_1                    --> 0.6.3-py36_0 conda-forge
    zlib:                1.2.8-3                         --> 1.2.11-0     conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda-env:           2.6.0-h36134e3_1                --> 2.6.0-0      conda-forge

Proceed ([y]/n)? y

bzip2-1.0.6-1. 100% |######################################################| Time: 0:00:00 582.14 kB/s
conda-env-2.6. 100% |######################################################| Time: 0:00:00 776.13 kB/s
java-jdk-8.0.9 100% |######################################################| Time: 0:01:12   1.77 MB/s
ncurses-5.9-10 100% |######################################################| Time: 0:00:00   1.66 MB/s
perl-5.22.0.1- 100% |######################################################| Time: 0:00:10   1.54 MB/s
zlib-1.2.11-0. 100% |######################################################| Time: 0:00:00 473.27 kB/s
parallel-20170 100% |######################################################| Time: 0:00:01 855.72 kB/s
perl-app-cpanm 100% |######################################################| Time: 0:00:00 717.84 kB/s
perl-threaded- 100% |######################################################| Time: 0:00:00   1.74 MB/s
perl-time-piec 100% |######################################################| Time: 0:00:00   2.17 MB/s
perl-yaml-1.24 100% |######################################################| Time: 0:00:00 465.35 kB/s
samclip-0.2-pl 100% |######################################################| Time: 0:00:00   5.21 MB/s
snpeff-4.3-3.t 100% |######################################################| Time: 0:00:14   1.40 MB/s
bwa-0.7.17-pl5 100% |######################################################| Time: 0:00:00   1.22 MB/s
htslib-1.3.2-0 100% |######################################################| Time: 0:00:01 827.29 kB/s
libdeflate-0.8 100% |######################################################| Time: 0:00:00 107.50 kB/s
perl-bioperl-1 100% |######################################################| Time: 0:00:02 832.80 kB/s
perl-exporter- 100% |######################################################| Time: 0:00:00  10.09 MB/s
perl-file-slur 100% |######################################################| Time: 0:00:00  10.67 MB/s
pycosat-0.6.3- 100% |######################################################| Time: 0:00:00 803.03 kB/s
vcflib-1.0.0_r 100% |######################################################| Time: 0:00:28   2.00 MB/s
bcftools-1.8-1 100% |######################################################| Time: 0:00:01   2.11 MB/s
freebayes-1.1. 100% |######################################################| Time: 0:00:08   1.14 MB/s
perl-list-more 100% |######################################################| Time: 0:00:00 420.57 kB/s
samtools-1.8-3 100% |######################################################| Time: 0:00:02 811.34 kB/s
snippy-4.0_dev 100% |######################################################| Time: 0:00:00  10.58 MB/s
conda-4.5.1-py 100% |######################################################| Time: 0:00:00 752.10 kB/s
```


CHECK
```
snippy --check
[10:37:20] This is snippy 4.0-dev
[10:37:20] Written by Torsten Seemann
[10:37:20] Obtained from https://github.com/tseemann/snippy
[10:37:20] Detected operating system: linux
[10:37:20] Enabling bundled linux tools.
[10:37:20] Found bwa - /home/sebastien/anaconda3/bin/bwa
[10:37:20] Found bcftools - /home/sebastien/anaconda3/bin/bcftools
[10:37:20] Found samtools - /home/sebastien/anaconda3/bin/samtools
[10:37:20] Found snpEff - /home/sebastien/anaconda3/bin/snpEff
[10:37:20] Found java - /home/sebastien/anaconda3/bin/java
[10:37:20] Found gzip - /bin/gzip
[10:37:20] Found samclip - /home/sebastien/anaconda3/bin/samclip
[10:37:20] Found parallel - /home/sebastien/anaconda3/bin/parallel
[10:37:20] Found freebayes - /home/sebastien/anaconda3/bin/freebayes
[10:37:20] Found freebayes-parallel - /home/sebastien/anaconda3/bin/freebayes-parallel
[10:37:20] Found fasta_generate_regions.py - /home/sebastien/anaconda3/bin/fasta_generate_regions.py
[10:37:20] Found vcfstreamsort - /home/sebastien/anaconda3/bin/vcfstreamsort
[10:37:20] Found vcfuniq - /home/sebastien/anaconda3/bin/vcfuniq
[10:37:20] Found vcffirstheader - /home/sebastien/anaconda3/bin/vcffirstheader
[10:37:20] Found snippy-vcf_to_tab - /home/sebastien/anaconda3/bin/snippy-vcf_to_tab
[10:37:20] Found snippy-vcf_report - /home/sebastien/anaconda3/bin/snippy-vcf_report
[10:37:20] Checking version: samtools --version is >= 1.7 - ok, have 1.8
[10:37:20] Checking version: bcftools --version is >= 1.7 - ok, have 1.8
[10:37:20] Checking version: freebayes --version is >= 1.1 - ok, have 1.1
[10:37:20] Checking version: snpEff -version is >= 4.3 - ok, have 4.3
[10:37:20] Dependences look good!
```
SNPS.LOG FILE
```
### cd /media/sebastien/Olorin/MARITIMUM-STRUCTURE-ANALYSIS

### /home/sebastien/anaconda3/bin/snippy --outdir ./ouput_test/ --ref ./TSTRAIn-ref/T_maritimum_NCIMB2154T.gbk --ctgs ./other_genomes/FASTAS/902.fasta

### samtools faidx reference/ref.fa


### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.04 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.79 seconds elapse.
[bwa_index] Update BWT... 0.03 sec
[bwa_index] Pack forward-only FASTA... 0.03 sec
[bwa_index] Construct SA from BWT and Occ... 0.42 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 1.722 sec; CPU: 1.309 sec

### mkdir reference/genomes && cp -f reference/ref.fa reference/genomes/ref.fa


### mkdir reference/ref && gzip -c reference/ref.gff > reference/ref/genes.gff.gz


### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

java.lang.RuntimeException: Error parsing property 'ref.8080.codonTable'. No such codon table 'Bacterial_and_Plant_Plastid'
	at org.snpeff.snpEffect.Config.createCodonTables(Config.java:165)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:626)
	at org.snpeff.snpEffect.Config.init(Config.java:468)
	at org.snpeff.snpEffect.Config.<init>(Config.java:114)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:292)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:341)
	at org.snpeff.SnpEff.run(SnpEff.java:1009)
	at org.snpeff.SnpEff.main(SnpEff.java:155)
```
