### ISSUE TITLE
the latest release crashed at snpEff

### ISSUE THREAD

**Issue by fengyuchengdu** [tseemann/snippy#212]
Hi Torsten,

I just upgraded it to the latest release and found out it crashed when entering snpEff step.

The screen output asked me to check the log file which is shown below

### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.12 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 4.26 seconds elapse.
[bwa_index] Update BWT... 0.07 sec
[bwa_index] Pack forward-only FASTA... 0.07 sec
[bwa_index] Construct SA from BWT and Occ... 1.25 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 5.838 sec; CPU: 5.776 sec

### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

Picked up _JAVA_OPTIONS: -Xms4096m -Xmx51200m

### bwa mem -t -Y -M -R '@RG\tID:115044bb_refWCHKP095649_chr\tSM:115044bb_refWCHKP095649_chr' -t 22 reference/ref.fa /home/zong/Desktop/20180806/test/115044bb_1.fq.gz /home/zong/Desktop/20180806/test/115044bb_2.fq.gz | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /tmp/snippy.27113. --threads 16 -m 2000M | samtools fixmate -m - - | samtools sort -l 0 -T /tmp/snippy.27113. --threads 16 -m 2000M | samtools markdup -T /tmp/snippy.27113. -r -s - - > snps.bam

READ 6904436 WRITTEN 6047148 
EXCLUDED 3476945 EXAMINED 3427491
PAIRED 3357058 SINGLE 70433
DULPICATE PAIR 814398 DUPLICATE SINGLE 42890
DUPLICATE TOTAL 857288

### snpEff ann -noLog -noStats -no-downstream -no-upstream -no-utr -t -c reference/snpeff.config -dataDir . ref snps.filt.vcf > snps.vcf

Picked up _JAVA_OPTIONS: -Xms4096m -Xmx51200m

############ log ends here#############

I thought probably something wrong with "Picked up _JAVA_OPTIONS: -Xms4096m -Xmx51200m", so I remove these java options and manually tried the last command, which was "/home/zong/programs_and_scripts/snippy/binaries/noarch/snpEff ann -noLog -noStats -no-downstream -no-upstream -no-utr -t -c reference/snpeff.config -dataDir . ref snps.filt.vcf > snps.vcf" and nothing on screen popped out.

I checked snps.filt.vcf which looked OK, but some errors were found in snps.vcf which is shown below

#############  snps.vcf starts here ################

[ERROR] [08/08/2018 19:01:07.729] [vcfWorkQueue-akka.actor.default-dispatcher-1] [ActorSystem(vcfWorkQueue)] Uncaught error from thread [vcfWorkQueue-akka.actor.default-dispatcher-1]
java.lang.NoSuchMethodError: sun.misc.Unsafe.monitorEnter(Ljava/lang/Object;)V
	at akka.routing.RoutedActorRef.newActorCell(Routing.scala:55)
	at akka.actor.LocalActorRef.<init>(ActorRef.scala:244)
	at akka.routing.RoutedActorRef.<init>(Routing.scala:27)
	at akka.actor.LocalActorRefProvider.actorOf(ActorRefProvider.scala:548)
	at akka.actor.ActorCell._actorOf(ActorCell.scala:374)
	at akka.actor.ActorCell.actorOf(ActorCell.scala:391)
	at org.snpeff.akka.Master.<init>(Master.java:63)
	at org.snpeff.akka.vcf.MasterVcf.<init>(MasterVcf.java:23)
	at org.snpeff.snpEffect.commandLine.eff.MasterEff.<init>(MasterEff.java:21)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff$1.create(SnpEffCmdEff.java:505)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff$1.create(SnpEffCmdEff.java:499)
	at akka.actor.Props$$anonfun$$init$$1.apply(Props.scala:124)
	at akka.actor.Props$$anonfun$$init$$1.apply(Props.scala:124)
	at akka.actor.ActorCell.newActor(ActorCell.scala:488)
	at akka.actor.ActorCell.create$1(ActorCell.scala:506)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:593)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:208)
	at akka.dispatch.Mailbox.run(Mailbox.scala:177)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

[ERROR] [08/08/2018 19:01:07.733] [vcfWorkQueue-akka.actor.default-dispatcher-2] [akka://vcfWorkQueue/user/masterVcf] null
java.lang.NullPointerException
	at akka.actor.ActorCell.invoke(ActorCell.scala:619)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:196)
	at akka.dispatch.Mailbox.run(Mailbox.scala:178)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

[ERROR] [08/08/2018 19:01:07.734] [vcfWorkQueue-akka.actor.default-dispatcher-4] [akka://vcfWorkQueue/user/masterVcf] error while creating actor
java.lang.NullPointerException
	at akka.actor.ActorCell.doRecreate(ActorCell.scala:707)
	at akka.actor.ActorCell.recreate$1(ActorCell.scala:540)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:594)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:208)
	at akka.dispatch.Mailbox.run(Mailbox.scala:177)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

[ERROR] [08/08/2018 19:01:07.734] [vcfWorkQueue-akka.actor.default-dispatcher-4] [akka://vcfWorkQueue/user/masterVcf] error while creating actor
java.lang.NullPointerException
	at akka.actor.ActorCell.doRecreate(ActorCell.scala:721)
	at akka.actor.ActorCell.recreate$1(ActorCell.scala:540)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:594)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:208)
	at akka.dispatch.Mailbox.run(Mailbox.scala:177)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

###################### snps.vcf ends here #####################

 any idea how to fix this ?

thanks much,

Yu

**Comment by tseemann** [comment]
How did you install it?
What does `snpEff -version` say?
What does `java -version` say?

**Comment by fengyuchengdu** [comment]
zong@zong-Precision-Tower-7810:~$ /home/zong/programs_and_scripts/snippy/binaries/noarch/snpEff -version
SnpEff	4.3t	2017-11-24

I also tried installing snpEff via linuxbrew (brewsci/bio/snpeff: stable 4.3t (bottled)), which still did not work.

zong@zong-Precision-Tower-7810:~$ java -version
java version "9.0.4"

java was installed from "jdk: stable 9.0.4 (bottled)" by linuxbrew

"_JAVA_OPTIONS: -Xms4096m -Xmx51200m" was added in the .bashrc. I have tried to remove this from bashrc and it still did not work

our computer has 64GB RAM

################################

The gbk file used was downloaded from NCBI. 
I tried extracting sequence from this gbk and ran snippy using this fasta reference and it worked perfectly.
I thought probably snpEff had issues using NCBI gbk, then I tried using gbk from prokka (same sequence) to re-run the command, however it failed again.

Thanks for your reply,

Yu

**Comment by tseemann** [comment]
I am working on the homebrew version of Snippy 4.x and the bioconda version, which I am hoping will resolve these problems.

Lots of people have issues with snpEff. Many of your isses look like `thread` issues.  You told snippy to use `22 threads` --- how many cpu cores does your computer have?   (it only has 64GB ram)

**Comment by fengyuchengdu** [comment]
12 cpu 24 threads

let me try with 12

**Comment by tseemann** [comment]
I think ultimately it is some sort of Java problem.   
Are you using a mix of brew, system tools, and tools within the snippy binaries folder?
There is probably a clash.

**Comment by fengyuchengdu** [comment]
reducing threads did not help.

I installed java 8 using "brew install jdk@8" and tried it again. It worked !

**Comment by tseemann** [comment]
@fengyuchengdu wow! that is good news!  so it seems snpEff.jar does not support Java 9.
Thank you for your effort.
I will try and find a way to handle this problem.

**Comment by tseemann** [comment]
I am using snpEff with java 9 ok so this is weird!

```
SnpEff  4.3t    2017-11-24

java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

**Comment by pvanheus** [comment]
@tseemann along with @fengyuchengdu I find that 8 (openjdk 8.0.192) works, but openjdk 9.0.7 from conda-forge channel does not.
