### ISSUE TITLE
snippy error

### ISSUE THREAD

**Issue by sekhwal** [tseemann/snippy#503]
I am running snippy using following command. However, it shows the following error..

snippy --cpus 8 --outdir variants --ref reference.gbk --R1 trimmed_S_010_R1.fastq.gz --R2 trimmed_S_010_R2.fastq.gz 

### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/snpeff/SnpEff has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

**Comment by sekhwal** [comment]
Next, it shows "Need bcftools --version >= 1.7 but you have 0 - please upgrade it." However, I have bcftools1.15 in my conda environment.

**Comment by apetkau** [comment]
See https://github.com/tseemann/snippy/issues/501#issuecomment-1083236553
