### ISSUE TITLE
libtabixpp.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by DorothyTamYiLing** [tseemann/snippy#570]
Hi,

I have this error that seemed to be coming from freebayes, I have googled but still have no idea of how to solve it.

### freebayes-parallel reference/ref.txt 8 -p 2 -P 0 -C 2 -F 0.05 --min-coverage 10 --min-repeat-entropy 1.0 -q 13 -m 60 --strict-vcf   -f reference/ref.fa snps.bam > snps.raw.vcf

vcfstreamsort: error while loading shared libraries: libtabixpp.so.0: cannot open shared object file: No such file or directory
vcfuniq: error while loading shared libraries: libtabixpp.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/bin/vcffirstheader", line 17, in <module>
    print(line.strip())
BrokenPipeError: [Errno 32] Broken pipe

Also, can I say that the mapping is completed without any error and I can use the bam file?

Please see the complete log file below.

Thanks,
Dorothy

### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.06 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 2.67 seconds elapse.
[bwa_index] Update BWT... 0.03 sec
[bwa_index] Pack forward-only FASTA... 0.03 sec
[bwa_index] Construct SA from BWT and Occ... 0.80 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 3.772 sec; CPU: 3.600 sec

### bwa mem  -Y -M -R '@RG\tID:SRR7209059_snippy\tSM:SRR7209059_snippy' -t 8 reference/ref.fa /home/ubuntu/Dorothy/assembly_analysis/SRR7209059_1_trimmed.fastq.gz /home/ubuntu/Dorothy/assembly_analysis/SRR7209059_2_trimmed.fastq.gz | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /tmp --threads 3 -m 2000M | samtools fixmate -m --threads 3 - - | samtools sort -l 0 -T /tmp --threads 3 -m 2000M | samtools markdup -T /tmp --threads 3 -r -s - - > snps.bam

COMMAND: samtools markdup -T /tmp --threads 3 -r -s - -
READ: 4820320
WRITTEN: 4716270
EXCLUDED: 697874
EXAMINED: 4122446
PAIRED: 4094516
SINGLE: 27930
DUPLICATE PAIR: 83648
DUPLICATE SINGLE: 20402
DUPLICATE PAIR OPTICAL: 0
DUPLICATE SINGLE OPTICAL: 0
DUPLICATE NON PRIMARY: 0
DUPLICATE NON PRIMARY OPTICAL: 0
DUPLICATE PRIMARY TOTAL: 104050
DUPLICATE TOTAL: 104050
ESTIMATED_LIBRARY_SIZE: 49421215

### freebayes-parallel reference/ref.txt 8 -p 2 -P 0 -C 2 -F 0.05 --min-coverage 10 --min-repeat-entropy 1.0 -q 13 -m 60 --strict-vcf   -f reference/ref.fa snps.bam > snps.raw.vcf

vcfstreamsort: error while loading shared libraries: libtabixpp.so.0: cannot open shared object file: No such file or directory
vcfuniq: error while loading shared libraries: libtabixpp.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/bin/vcffirstheader", line 17, in <module>
    print(line.strip())
BrokenPipeError: [Errno 32] Broken pipe

**Comment by Alejandro-PI** [comment]
Hi!
The problem occurs because libtabixpp.so.0 is missing.
install libtabixpp.0
`sudo apt-get update`
`sudo apt-get install libtabixpp0`

**Comment by jolespin** [comment]
@DorothyTamYiLing this worked for me: 

```
mamba install -c bioconda tabixpp==1.1.0
```

**Comment by JamesZlosnik** [comment]
Thank you for this!!  I recently did a fresh install of Nullarbor and it failed with this error.  When I went to apply 

```
mamba install -c bioconda tabixpp==1.1.0
```

mamba told me that the installed version was 1.1.2 and to install 1.1.0 it would also have to install `bc`.

Once I did this, Nullarbor worked again.

**Comment by jolespin** [comment]
I'm not sure if this tool is being actively developed so I've been using https://github.com/dmnfarrell/snipgenie 

Usage is similar with the biggest difference being that you need a manifest file which is straightforward to create
